//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job_Portal.context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_3
    {
        public int id { get; set; }
        [Required(ErrorMessage ="Enter Name")]
        public string name { get; set; }
        [Required(ErrorMessage = "Enter rollno")]
        public Nullable<int> rollno { get; set; }
        [Required(ErrorMessage = "Enter phone")][MinLength(10,ErrorMessage ="Enter correct Mobile")]
        public string phone { get; set; }
        [Required(ErrorMessage = "Enter Email")][EmailAddress]
        public string Email { get; set; }
    }
}
